# Generated by Django 3.2.1 on 2021-06-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/img/')),
                ('author', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=250)),
                ('reyting', models.SmallIntegerField()),
            ],
        ),
    ]
